In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# Creating Dataset

features = torch.rand(10, 5)

# Create Model

model = Model(features.shape[1])

# Call Model for Forward pass

model(features)

tensor([[0.4383],
        [0.4051],
        [0.4252],
        [0.4168],
        [0.3912],
        [0.4402],
        [0.4164],
        [0.3218],
        [0.3993],
        [0.5054]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Show Model Weights

model.linear.weight

Parameter containing:
tensor([[-0.3971, -0.2051,  0.2351,  0.0727, -0.4041]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## **Hidden Layer & Relu**

In [ ]:
class Model1(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [ ]:
# Creating Dataset

features = torch.rand(10, 5)

# Create Model

model1 = Model1(features.shape[1])

# Call Model for Forward pass

model1(features)

tensor([[0.6134],
        [0.5549],
        [0.6422],
        [0.5840],
        [0.6063],
        [0.5477],
        [0.5770],
        [0.5393],
        [0.5776],
        [0.6028]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Show Model Weights

model1.linear1.weight

Parameter containing:
tensor([[-0.0786, -0.3748,  0.3512,  0.3534,  0.1576],
        [-0.0119, -0.4051,  0.4339,  0.4258, -0.0104],
        [-0.0651, -0.2683, -0.3597, -0.0662,  0.1918]], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## **Sequential Container**

In [ ]:
class Model2(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
# Creating Dataset

features = torch.rand(10, 5)

# Create Model

model2 = Model2(features.shape[1])

# Call Model for Forward pass

model2(features)

tensor([[0.3642],
        [0.3386],
        [0.3222],
        [0.3642],
        [0.3642],
        [0.3654],
        [0.3330],
        [0.3168],
        [0.3172],
        [0.3642]], grad_fn=<SigmoidBackward0>)

In [30]:
# Show Model Weights

model2.network[0].weight

Parameter containing:
tensor([[ 0.1902,  0.1586,  0.3798, -0.0847, -0.2555],
        [-0.3573, -0.2707,  0.0738, -0.0123,  0.0328],
        [-0.2194, -0.3468, -0.3628,  0.4198,  0.2807]], requires_grad=True)

In [31]:
from torchinfo import summary

summary(model1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00